### ISSUE TITLE
Ice server url necessary with last version of android client

### ISSUE THREAD

**Issue by juanjosv** [ISBX/apprtc-node-server#13]
I use this client for android system, i can connect to appr.tc or apprtc.appspot without problem, but i need my own server and this apprtc node server is a very good option, but with this android client is necesary add a new parameter in the json returned by the /join/ post event, if you compare the json returned from the other two server with this one, i think the json is a bit obsolete.
I had modify the **routes/index.js** file with the next code:

var iceServerUrl = "https://Your_ice_server";

var params ={
[...]
'ice_server_url': iceServerUrl
};
Maybe this is not a good solution, but a working solution.

**Comment by dr-fusion** [comment]
I have installed ejabberd in same server.
Can you tel me what should be value of icerServerUrl="abc.maindomain.com"
or something different?

**Comment by hassaan-dev** [comment]
@juanjosv on which **line number** or **near by line**, you put this code?

**Comment by sandeeptaz** [comment]
@juanjosv hi..please let me know on which line number have u put this code.

**Comment by juanjosv** [comment]
That was a couple of years ago, and maybe the versión has changed. The code is in the params to connect.
