### ISSUE TITLE
no turn server 

### ISSUE THREAD

**Issue by invisiblecoder99** [ISBX/apprtc-node-server#15]
No TURN server; unlikely that media will traverse networks. If this persists please report it to discuss-webrtc@googlegroups.com.

please provide actual fix please

**Comment by ghost** [comment]
You probably have problem with TURN server parameters in routes/index.js file:
TURN_BASE_URL : 'turn:turnserverurl:port',
TURN_URL_TEMPLATE : '%s/turn?username=%s&key=%s',
CEOD_KEY : 'turnserverkey',

It seems that old public turn servers doesn't work anymore. You can install your own TURN server (https://github.com/coturn/coturn), and then change parameters accordingly:

TURN_BASE_URL : 'turn:YourTurnUrl.com:port', //port is usually 3478 if you haven't change it
TURN_URL_TEMPLATE : '%s/turn?username=%s&key=%s', //this line stay the same
CEOD_KEY : '84ac8666fb8024', // key is from /etc/turnuserdb.conf 's username:key pair, eg. turnusername:84ac8666fb8024

**Comment by nimblemo** [comment]
Can you specify the start of the turn server in detail? It has many startup options.

**Comment by fais3000** [comment]
@savo-borne Thanks for the pointers. I set up my own turn server using you info. Video chat is now working on Firefox and Android chrome but for some reason, it doesn't on chrome.

 I get 

> XMLHttpRequest cannot load XMLHttpRequest cannot load turn:hostname:3478/turn?username=username&key=key&transport=udp Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

I tried replacing the hostname with IP as well, but no success.

**Comment by sandeeptaz** [comment]
@fais3000  please let me know what changes u did to ur file in order to set turn url and credentials.
Thank you in advance
